services:
    phpbb.collapsiblecategories.operator:
        class: phpbb\collapsiblecategories\operator\operator
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @user
