services:
    phpbb.collapsiblecategories.controller:
        class: phpbb\collapsiblecategories\controller\main_controller
        arguments:
            - @phpbb.collapsiblecategories.operator
            - @request
